[pytest]
testpaths = tests

addopts =
    --tracing=retain-on-failure
    --video=retain-on-failure
    --screenshot=only-on-failure
    --html=reports/html/report.html
    --self-contained-html
    --output=reports/artifacts
    --slowmo=1000