[pytest]
testpaths = tests

addopts =
    --browser=chromium
    --tracing=retain-on-failure
    --video=retain-on-failure
    --screenshot=only-on-failure
    --html=reports/html/report.html
    --self-contained-html
    --output=reports/artifacts
    --junit-xml=reports/junit/results.xml