[pytest]
testpaths = tests

addopts =
    --headed
    --tracing=retain-on-failure
    --video=retain-on-failure
    --screenshot=only-on-failure
    --self-contained-html
    --html=reports/report.html --self-contained-html